[flake8]
exclude = .git
ignore = E124, W503, W291, W293
max-line-length = 88

[tox]
envlist = py36, py37, py38, py39, py310, py311, docs, pylint
isolated_build = True

[testenv]
deps=
    requests-mock
    coverage
commands=
    coverage run -m unittest
    coverage xml
    coverage report -m

[testenv:docs]
description = invoke sphinx-build to build the HTML docs
skip_install = True
deps = -r{toxinidir}/docs/requirements.txt
install_command = python -I -m pip install {opts} {packages}
commands =
    sphinx-build -d "{toxworkdir}/docs_doctree" docs "{toxworkdir}/docs_out" --color -W -bhtml {posargs}


[testenv:pylint]
deps=
    requests-mock
    pylint

commands=
    pylint dhooks_lite
